#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s="  " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry=$(mediainfo "$1" | grep -iE "(width|height)" | sed "s/ pixels//; s/Width//; s/Height//" | tr '\n' ' ' | xargs -0 printf "%s\n" | awk -F ':' '{print $2 "x" $3}' | sed -e "s/[[:space:]]\{1,\}//g")


echo "${filesize}${s}${geometry}${s}${filename}"

