#!/bin/sh
# Profile file. Runs on login.
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

export LANG=en_US.UTF-8
export EDITOR="nvim"
export TERM="st-256color"
export TERMINAL="st"
export FILE="lf"
export BROWSER="helium"
export READER="zathura"

# XDG
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DESKTOP_DIR="$HOME/desk"
export XDG_DOCUMENTS_DIR="$HOME/dox"
export XDG_DOWNLOAD_DIR="$HOME/down"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pix"
export XDG_VIDEOS_DIR="$HOME/vids"

export XAUTHORITY="$XDG_DATA_HOME/Xauthority"

export USER_OPT_DIR="$HOME/opt"

export ASDF_DIR="$USER_OPT_DIR/asdf"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_GEM_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/asdf/default_gems"

export LESSHISTFILE="$XDG_CACHE_HOME/lesshst"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export _ZL_DATA="$XDG_DATA_HOME/z"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export NOTMUCH_CONFIG=/home/ttr3dp/.config/.notmuch-config
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export NPM_PACKAGES="$XDG_DATA_HOME/npm/.npm-packages"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

export GOPATH="$XDG_DATA_HOME/go"
export PATH="$GOPATH/bin:$NPM_PACKAGES/bin:$PATH"

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_ENABLE_HIGHDPI_SCALING=1
__GL_SHADER_DISK_CACHE="0"

# Switch escape and caps if tty:
sudo -n loadkeys ~/.config/ttymaps.kmap 2> /dev/null

# Start graphical server if one is not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg > /dev/null && startx
