#!/bin/sh
# Profile file. Runs on login.
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

export LANG=en_US.UTF-8
export EDITOR="nvim"
export TERMINAL="st"

# XDG
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DESKTOP_DIR="$HOME/desk"
export XDG_DOCUMENTS_DIR="$HOME/dox"
export XDG_DOWNLOAD_DIR="$HOME/down"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pix"
export XDG_VIDEOS_DIR="$HOME/vids"

export XAUTHORITY="$XDG_DATA_HOME/Xauthority"

export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export _Z_DATA="$XDG_DATA_HOME/z"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

__GL_SHADER_DISK_CACHE="0"

# Switch escape and caps if tty:
sudo -n loadkeys ~/.config/ttymaps.kmap 2> /dev/null

# Start graphical server if one is not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg > /dev/null && exec startx

